prog_cover:
  description: "Set the cover into prog mode"
  fields:
    entity_id:
      description: "The entity ID of the cover"
      example: cover.somfy_cul_abcd
open_cover:
  description: "Open the cover"
  fields:
    entity_id:
      description: "The entity ID of the cover"
      example: cover.somfy_cul_abcd
close_cover:
  description: "Close the cover"
  fields:
    entity_id:
      description: "The entity ID of the cover"
      example: cover.somfy_cul_abcd
stop_cover:
  description: "Stop the cover"
  fields:
    entity_id:
      description: "The entity ID of the cover"
      example: cover.somfy_cul_abcd
reload_state:
  description: "Reload the state YAML file"
  fields:
    entity_id:
      description: "The entity ID of the cover"
      example: cover.somfy_cul_abcd